version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: "marycode/template-nestjs"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - STAGE=$STAGE
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - "80:80"
