name: Deploy nestjs-travel-api
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nestjs-travel-api .

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/nestjs-travel-api

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: nest-travel-aws
          environment_name: Nest-travel-aws-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-146463422607
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true